CREATE TABLE PRODUTO (
   ID INT PRIMARY KEY, 
   ATIVO BOOLEAN, 
   CADASTRO   DATE, 
   NOME VARCHAR, 
   QUANTIDADE INT
);
-- JSON-> {"id":0,"nome":"CADEIRA BANCO","ativo":true,"cadastro":"2020-11-10T00:00:00.000","quantidade":12}
	INSERT INTO PRODUTO (ID, ATIVO, CADASTRO, NOME, QUANTIDADE) 
	              VALUES (1, TRUE, '2020-11-01', 'COMPUTADOR DESKTOP', 10);
	INSERT INTO PRODUTO (ID, ATIVO, CADASTRO, NOME, QUANTIDADE) 
	              VALUES (2, TRUE, '2020-12-11', 'MESA ESCRITÓRIO', 2);
	INSERT INTO PRODUTO (ID, ATIVO, CADASTRO, NOME, QUANTIDADE) 
	              VALUES (3, TRUE, '2020-02-22', 'CADEIRA EXECUTIVA', 7);              